[API/CLI] Cron routes
speedianet/sam pull request #1
Opened 2023-09-18 05:39 UTC by matheusmpolillo

## API
- New repository (_command_)
- New use cases (Add, Update and Delete)
- New repository test case
- New routes (`POST - /cron`, `PUT - /cron` and `DELETE - /cron/{cronId}`)

## CLI
- New repository (_command_)
- New use cases (Add, Update and Delete)
- New repository test case
- New command (`add`, `update` and `delete`)

2023-09-18 13:23 UTC, ntorga requested changes

2023-09-18 13:23 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +}
Você cria o arquivo em uma função e remove na outra. Isso é uma prática desaconselhável:
https://refactoring.guru/smells/shotgun-surgery

Se você mudar o nome do arquivo, você também precisará mudar em vários lugares pois ele está hard-coded e não foi exportado pra struct... se é uma variável/constante de uso compartilhado, o certo seria reaproveitá-la no contexto da struct.

De qualquer maneira, voltando a lógica em si usada para implementar a infra, acho que poderíamos seguir um caminho mais produtivo.

Veja, você precisa trabalhar com crontabs, que são arquivos que 99.999% das vezes terão 1kb. Isso pode ser armazenado em memória através de uma string multi-linha.

Dessa maneira você não realiza nenhuma operação em disco diretamente, sempre interfacenado pelo binário do crontab:

1) crie um constructor pra sua classe que leia a crontab pra []entity.Cron e armazene em uma variável que estará disponível para todos seus métodos do repositório (a.k.a use o método Get() do queryRepo direto no construct do CmdRepo).

2) crie um método que atualize a crontab e chame esse método sempre que você modificar o cron, seja para add/editar/remover.

3) No método update, você não precisa da entidade, você já terá todos os crons na variável que armazena todos os crons e com base nele, você consegue modificar apenas o que precisa e chamar o método de salvar.

2023-09-18 13:23 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	cronjobSchedule = cron.Schedule.String()
Tem hora que você chama "cron" de "cron" e hora que chama de "cronjob". É importante para legibilidade e manutenção que exista um padrão único, para quem estiver lendo não achar que são duas coisas diferentes.

2023-09-18 13:23 UTC, ntorga commented on src/infra/cronCmdRepo_test.go
> +	addCron := dto.AddCron{
Seu DTO não possui um constructor? Acredito que é melhor usá-lo do que instanciar a struct diretamente.

2023-09-18 13:23 UTC, ntorga commented on src/infra/cronCmdRepo_test.go
> +	return nil
Como falei acima, return err aqui é o suficiente, teu if é redundante.

2023-09-18 13:23 UTC, ntorga commented on src/infra/cronCmdRepo_test.go
> +		err := addDummyCron()
Vejo que você separou a lógica de criação de cron para uma função addDummyCron, mas só chama ela aqui. Isso é uma separação de código desnecessário do momento e se não há necessidade no momento, não desenvolvemos, princípio KISS no caso.

2023-09-18 13:23 UTC, ntorga commented on src/infra/cronCmdRepo_test.go
> +			t.Errorf("UnexpectedError: %v", err)
Você definiu que o cron id 1 não existirá. Se você executar o teste de add duas vezes, ele não passará a existir? Eu separaria o cronId em uma variável "cronId = valueObject.NewCronIdPanic(1000)" e daí chamaria o Delete, as chances de alguém repetir o teste unitário mil vezes é bem baixa.

2023-09-18 13:23 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +	cronsQueryRepo := infra.CronQueryRepo{}
cronQueryRepo

2023-09-18 13:23 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +		valueObject.NewCronIdPanic(requestBody["id"].(interface{})),
Por que o cast pra .(interface{}) aqui?

2023-09-18 13:23 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +// @Router       /cron/{cronId} [delete]
Faltando o / no final.

2023-09-18 13:25 UTC, matheusmpolillo commented on src/domain/repository/cronCmdRepo.go
> +	Update(cronjob entity.Cron, updateCron dto.UpdateCron) error
O `cronjob entity.Cron` é o retorno do `GetById` do `cronQueryRepo` uma vez que eu farei as alterações em cima do cronjob já existente no método de `Update` ao invés de só reescrevê-lo. Como o método `GetById` retorna uma entidade do tipo `Cron`, então eu só a passo pra frente.

2023-09-18 13:37 UTC, matheusmpolillo commented on src/infra/cronCmdRepo.go
> +	cronjobSchedule = cron.Schedule.String()
Com a mudança de uma das variáveis de `cronjob` para `cronLine` acho que vai ficar mais fácil de entender, principalmente porque usei a nomenclatura "cron" de forma reservada apenas as entidades e DTOs. Acha que ainda pode dar ruim mesmo com a mudança de `cronjob` para `cronLine` mais acima?

2023-09-18 13:53 UTC, matheusmpolillo commented on src/infra/cronCmdRepo.go
> +}
Tenho algumas dúvidas em relação a isso.

Na última vez que foi tratado sobre como manipular o _crontab_ foi dito que não havia problema em fazê-lo por manipulação de arquivo, portanto como eu já tinha esse modelo pronto decidi mantê-lo dessa forma.

Quanto a criação e remoção do arquivo, ele estaria se comportando como um arquivo temporário, não consegui ver a semelhança com **Shotgun Surgery**, já que o conteúdo original é copiado para o arquivo temporário, este recebe um _cronjob_ novo e/ou tem outro removido, depois é passado este novo conteúdo como _overwirte_ para o arquivo original, algo muito parecido com dar um `echo` pra dentro do arquivo original.

Quanto a alteração do nome ao longo do arquivo, ele utiliza um parâmetro que recebe como valor um unixTimestamp que é compartilhado ao longo de todos os métodos de acordo com o método principal chamado, como `Add` ou `Update`. Esse dado está imutável ao longo do arquivo, então faria mesmo sentido ter uma `struct` reservada para toda essa operação só por uma constante?

São só algumas coisas que fiquei curioso sobre.

2023-09-18 13:53 UTC, matheusmpolillo commented on src/infra/cronCmdRepo_test.go
> +	addCron := dto.AddCron{
Fiz baseado no teste do accCmdRepo, não imaginei que poderia ser um problema. Vou ajeitar!

2023-09-18 14:04 UTC, matheusmpolillo commented on src/infra/cronCmdRepo_test.go
> +			t.Errorf("UnexpectedError: %v", err)
Na verdade é o contrário, estou cogitando que o `cronId = 1` irá existir, tendo em vista que estou trabalhando com o fato de que só irá dar erro caso `err != nil` e isso só irá ocorrer, na atual situação, caso o `cronId = 1` não exista.

2023-09-18 14:46 UTC, matheusmpolillo commented on src/presentation/api/controller/cronController.go
> +	)
Porque você usa um _middleware_ que faz a adição do "/" no final de toda rota, isso estava enviando o "/" para dentro do parâmetro `cronId`. Quando eu batia uma _request_ passando 1 no `cronId`, por exemplo, o parâmetro vinha como "1/", por isso foi necesário o `TrimRight`.

2023-09-18 16:26 UTC, ntorga commented on src/domain/repository/cronCmdRepo.go
> +	Update(cronjob entity.Cron, updateCron dto.UpdateCron) error
Mas por que você precisaria passar ele pra frente? Não é mais fácil você usar o GetById direto na implementação do Update? Você colocar ele no domínio só deixou seu código e lógica mais complexa, entende?

2023-09-18 16:56 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +}
1. Não há problema em fazer manipulação de arquivo, contanto que essa seja uma implementação simples. O cerne do código limpo é leitura, que permite manutenibilidade.
 
Você precisou explicar seu código pra mim, código limpo não há necessidade de explicação, salva raríssimas exceções onde nós temos que usar comentários e tem que ser raro mesmo pois comentário em código é também Code Smell.

Vou tentar te explicar a questão de legibilidade, vamos à primeira função:
```
func editCrontab(crontabContent string, cronUnixTimestampStr string, delete bool) error {
```

Sem ler o que ela faz, o que você assume que ela faz? Aparentemente recebe todo o conteúdo do arquivo cron e usa algum tipo de timestamp, bem como permite deletar o arquivo? Oi? Esse método faz duas coisas?

Daí quando você vai pra essa função:
```
func removeCronjob(line string, cronUnixTimestampStr string) error {
```

Você aparentemente precisa passar a linha (o cron em formato de linha ou será que é o número da linha) e o tal do timestamp de novo (pq isso?).

Daí vamos pro próximo método:
```
func importCurrentCrontab(timeSuffix string) error {
```

Pelo nome me parece ser um método que importa um crontab mas o retorno é somente error... importa pra onde? E o que seria esse timeSuffix, novamente com timestamp, mas cron não tem nada a ver com isso.

Por fim, temos:
```
func installNewCrontab(timeSuffix string) error {
```

Ok, esse instala um novo crontab, mas qual crontab? Esse método não pertence a nenhuma struct e fica me pedindo esse tal de timeSuffix.

Pronto, esse é o entendimento que um DevOps às 3 da manhã vai tentar entender por que algo tá dando errado no código. Sua implementação não tá simples de entender, eu que sou dev tive dificuldade de entender sua automação, pensa no DevOps. É um código que funciona, mas pouco legível.

Seu installNewCrontab compartilha um valor hard-coded de outro método e além de fazer o que ele propõem, ele também deleta o arquivo temporário. Teu importCurrentCrontab também usa um valor hard-coded, tá com nome errado (a gente importa algo DE um lugar PARA o outro) e por aí vai.

O objetivo do dev é converter pseudo-código, ou seja, a lógica, o fluxograma que tu imaginou pra sua automação, em código. Aqui temos um código cuja lógica não é clara, tá claramente centrado em funcionar e não preocupado em ser mantido ou lido.

2. Você comentou:

```
Quanto a alteração do nome ao longo do arquivo, ele utiliza um parâmetro que recebe como valor um unixTimestamp que é compartilhado ao longo de todos os métodos de acordo com o método principal chamado, como Add ou Update. Esse dado está imutável ao longo do arquivo, então faria mesmo sentido ter uma struct reservada para toda essa operação só por uma constante?
```

Não precisa de nova struct. Se esses métodos são usados somente pelo cronCmdRepo, por que eles não pertencem a struct (ou seja, se iniciam com "func (repo CronCmdRepo)" ), daí eles poderiam acessar constantes ou variáveis que pertencem ao CronCmdRepo.

2023-09-18 16:58 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +	)
Mas se você add o / no final, você não vai receber o / no c.Param. Não?

2023-09-18 16:59 UTC, ntorga commented on src/infra/cronCmdRepo_test.go
> +	addCron := dto.AddCron{
Se lá estiver assim, deve ter um motivo, provavelmente algum param que não é necessário para o teste ou foi criado errado mesmo e precisa ser corrigido. Aqui nesse caso não há necessidade de fazer sem usar o constructor.

2023-09-18 17:00 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	cronjobSchedule = cron.Schedule.String()
Depende, vai dificultar a leitura? Pois usar cron e cronjob e eles terem ideias diferentes, não fica claro pro leitor.

2023-09-18 20:52 UTC, matheusmpolillo commented on src/domain/repository/cronCmdRepo.go
> +	Update(cronjob entity.Cron, updateCron dto.UpdateCron) error
Faz total sentido, agora saquei o que você quis dizer. Vou fazer a alteração!

2023-09-22 12:03 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	return err
Se o único retorno do os.Remove é um error, então a criação da var err aqui é redundante, você pode usar return direto. 

Eu só não entendi por que você criou um método delCronTabTmpFile se ele é usado apenas por um único método e ele tem apenas uma linha. Me parece que o método em si é redundante e poderia estar direto no método que o chama.

2023-09-22 12:08 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	}
O que esse for está fazendo exatamente? Tenho a impressão de que ele converte um []entity.Cron em um arquivo de texto, mas não tenho certeza... se esse é o propósito dele, então você deveria ter criado um método auxiliar para deixar isso mais claro. Fiquei encucado com a sua lógica de criação de método auxiliar, você separou o delete ali em cima em um método mesmo ele sendo apenas 1 única linha de código e bem fácil de entender mas deixou essa parte aqui que não dá pra ter certeza do que faz só ao ler, dentro do método principal.

2023-09-22 12:09 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	return err
err redundante, você pode retornar o output direto se o output for apenas err.

2023-09-22 12:10 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +
Imagino que essa linha aqui de espaçamento não tenha necessidade se o crontabContent será usado logo em seguida. Geralmente separamos um item do outro por responsabilidade/escopo, no caso, ambos são do mesmo escopo e responsabilidade.

2023-09-22 12:10 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +		valueObject.NewCronIdPanic(len(repo.currentCrontab)+1),
Jamais use Panic fora da presentation ou testes unitários.

Essa lógica "(repo.currentCrontab)+1" poderia ser uma variável explicando do que se trata, o próximo dev a manter esse código não vai entender com certeza.

2023-09-22 12:13 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	return err
err redundante, retorne direto o output.

2023-09-22 12:14 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	cronIndex := updateCron.Id.Get() - 1
Por que é necessário ter um -1 aqui? Não entendi a lógica, mesmo ao ler o código todo. Se o método update vai alterar um cron que existe e portanto você tem o ID dele, por que você não usa o GetById para pegar o entity.Cron, modifica ele ao criar um novo editado e depois o substitui? Outra opção é um for loop no currentCrontab para encontrar o entity que você precisa.

Vai ficar bem mais legível e seguro, já que você está substituindo um objeto pelo outro ao invés de fazer modificações em um que já existe. Imutabilidade é crucial em processo de alterações, pois ao trocar um objeto pelo outro você garante a integridade dele no final.

2023-09-22 12:16 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	return err
err redundante, retorne o output direto.

2023-09-22 12:16 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	)
O que eu falei acima, se aplica aqui novamente.

2023-09-22 12:23 UTC, ntorga commented on src/infra/cronCmdRepo_test.go
> +		err = cronCmdRepo.Add(addCron)
Vi que você referencia o ID 1 ali no Update/Delete.. quando você add pela primeira vez um cron ele usa o ID 1 ao invés de 0?

2023-09-22 12:25 UTC, ntorga commented on src/infra/cronQueryRepo.go
> +		foundCronjob = true
```
    return cronjob, nil
}

return entity.Cron{}, errors.New("CronNotFound")
```

Com isso você torna o requestedCronjob e foundCronjob redundantes e deixa seu código mais curto sem atrapalhar legibilidade.

2023-09-22 12:27 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +
Linha 129 é redundante.

2023-09-25 20:37 UTC, matheusmpolillo commented on src/infra/cronCmdRepo_test.go
> +		err = cronCmdRepo.Add(addCron)
O ID do Cron é diferente do índice dele na lista. Em um _slice_ o primeiro elemento sempre será o 0, mas em um arquivo o primeiro elemento sempre estará na linha 1. Ou seja, o ID do Cron faz referência a linha em que ele se encontra no _crontab_ e não a posição dele no _slice_.

2023-09-26 13:05 UTC, ntorga requested changes

2023-09-26 13:05 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +// @Description  Delete an cron.
Delete a cron.

2023-09-26 13:05 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +// @Description  Update an cron.
Update a cron.

2023-09-26 13:05 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +// @Description  List Crons.
List crons.

2023-09-26 13:05 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +	}
Por que aqui seria erro 4xx e não 5xx?

2023-09-26 13:05 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +	}
BadRequest ou InternalServerError?

2023-09-26 13:05 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +		return apiHelper.ResponseWrapper(c, http.StatusBadRequest, err.Error())
BadRequest ou InternalServerError?

2023-09-26 15:45 UTC, matheusmpolillo commented on src/presentation/api/controller/cronController.go
> +	}
Segui a mesma lógica do AccountController. Como ele era uma entidade muito próxima do que queria fazer no Cron, me baseei nele.

Além disso, todos os possíveis erros do _use case_ **AddCron** são relacionados a VOs e entidades, não há nenhuma interação com sistema externos. No construtor do repositório ele utiliza o **QueryRepo** pra buscar os registros. Por ser manipulação de arquivo e estar relacionado apenas a um processo de _read_, não vejo motivos para retornar um 500, principalmente por 100% dos erros serem relacionados a domínio.

2023-09-26 15:48 UTC, matheusmpolillo commented on src/presentation/api/controller/cronController.go
> +	}
Me baseei no AccountController.

Além disso, esse _use case_, assim como o de adicionar, só tem erros de domínio. Não vejo motivos para retornar 500 ao invés de 400 enquanto os possíveis erros são apenas de domínio (VO e entidade).

2023-09-26 15:56 UTC, matheusmpolillo commented on src/presentation/api/controller/cronController.go
> +		return apiHelper.ResponseWrapper(c, http.StatusBadRequest, err.Error())
Me baseei no AccountController.

Além disso, esse _use case_, assim como o de adicionar, só tem erros de domínio. Não vejo motivos para retornar 500 ao invés de 400 enquanto os possíveis erros são apenas de domínio (VO e entidade).

2023-09-26 20:09 UTC, ntorga requested changes

2023-09-26 20:09 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	}
currentCrontabContent aqui não é o cron em si? Acho que você intencionou:
```
for _, cron := range repo.currentCrontab
```

2023-09-26 20:09 UTC, ntorga commented on src/infra/cronCmdRepo.go
> +	newCronId, err := valueObject.NewCronId(updatedCronId)
updatedCron e newCron são elementos diferentes? Acho que você usou duas nomenclatures para a mesma coisa, não?

2023-09-26 20:09 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +	}
Olha pra linha 27, lá é usado o erro 500. Se no AccountController tá retornando 400 deve ser pq tá errado. É importante entender o motivo para que você não copie o erro de outro lado do código e sim corrija no seu e no outro.

Não tem nada no usecase que retornaria erro 400, pois você está validando todos os VOs no presenter com o Panic. Qualquer erro retornado pelo AddCron vai ser erro de infra, portanto 500.

2023-09-26 20:09 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +	}
Respondido acima.

2023-09-26 20:09 UTC, ntorga commented on src/presentation/api/controller/cronController.go
> +		return apiHelper.ResponseWrapper(c, http.StatusBadRequest, err.Error())
Respondido acima.

2023-09-27 16:07 UTC, matheusmpolillo commented on src/infra/cronCmdRepo.go
> +	}
Mantive a nomenclatura **currentCrontab** para fazer referência à propriedade do _struct_ e complementei com **Content** para simbolizar que é o conteúdo dos **crons** desse vetor. Mas a mudança solicitada faz sentido mesmo, colocarei ela!

2023-09-27 20:07 UTC, ntorga approved these changes

2023-09-27 20:07 UTC, merged